# Generated by Django 4.2.3 on 2023-08-05 08:48

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='last_name')),
                ('status', models.CharField(choices=[('', '-----'), ('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff')], default='', max_length=10)),
                ('DOB', models.DateField(default=django.utils.timezone.now)),
                ('Gender', models.CharField(choices=[('', '------'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('phone_1', models.CharField(default='', max_length=10)),
                ('phone_2', models.CharField(default='', max_length=10)),
                ('Aadhar_Number', models.CharField(blank=True, default='', max_length=12)),
                ('Fathers_Name', models.CharField(default='', max_length=100)),
                ('Fathers_Occupation', models.CharField(blank=True, max_length=100)),
                ('Mothers_Name', models.CharField(default='', max_length=100)),
                ('Mothers_Occupation', models.CharField(blank=True, max_length=100)),
                ('House_No', models.CharField(default='', max_length=100)),
                ('Street_Name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('PIN_Code', models.CharField(default='', max_length=10)),
                ('Category', models.CharField(choices=[('', '------'), ('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='', max_length=20)),
                ('Profile_pic', models.ImageField(default='default.jpg', upload_to=users.models.path_and_rename)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
