# Generated by Django 3.0.8 on 2020-07-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_edit_student_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Create_New_Entry',
            field=models.BooleanField(default=False),
        ),
    ]
