# Generated by Django 3.0.8 on 2020-07-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_no', models.IntegerField(default=0, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default='YYYY-MM-DD')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('Phone', models.IntegerField()),
                ('Phone_Other', models.IntegerField(blank=True, default=0)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Address', models.TextField(max_length=300)),
                ('Fathers_Name', models.CharField(max_length=100)),
                ('Fathers_Occupation', models.CharField(blank=True, max_length=100)),
                ('Mothers_Name', models.CharField(max_length=100)),
                ('Mothers_Occupation', models.CharField(blank=True, max_length=100)),
                ('Relegion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('', 'Choice'), ('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='', max_length=20)),
                ('Nationality', models.CharField(default='Indian', max_length=50)),
                ('Note_about_Student', models.TextField(blank=True, max_length=500)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('remaning_fees', models.IntegerField(default=-1)),
                ('paid_fees', models.IntegerField(default=0)),
                ('Profile_pic', models.ImageField(default='', upload_to=students.models.path_and_rename)),
                ('Aadhar_Card', models.ImageField(blank=True, default='', upload_to=students.models.path_and_rename)),
                ('Marksheet_10th', models.ImageField(blank=True, default='', upload_to=students.models.path_and_rename)),
                ('Marksheet_12th', models.ImageField(blank=True, default='', upload_to=students.models.path_and_rename)),
                ('Caste_Certificate', models.ImageField(blank=True, default='', upload_to=students.models.path_and_rename)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
