# Generated by Django 3.0.8 on 2020-07-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Phone_Other', models.IntegerField(blank=True, max_length=10)),
                ('Address', models.TextField(max_length=300)),
                ('Fathers_Name', models.CharField(max_length=100)),
                ('Fathers_Occupation', models.CharField(blank=True, max_length=100)),
                ('Mothers_Name', models.CharField(max_length=100)),
                ('MOthers_Occupation', models.CharField(blank=True, max_length=100)),
                ('Relegion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('Nationality', models.CharField(default='Indian', max_length=50)),
                ('Note_about_Student', models.CharField(blank=True, max_length=500)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
