# Generated by Django 3.0.8 on 2020-07-09 16:56

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Aadhar_Card',
            field=models.ImageField(default='default.jpg', upload_to=students.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='student',
            name='Caste_Certificate',
            field=models.ImageField(default='default.jpg', upload_to=students.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='student',
            name='Marksheet_10th',
            field=models.ImageField(default='default.jpg', upload_to=students.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='student',
            name='Marksheet_12th',
            field=models.ImageField(default='default.jpg', upload_to=students.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='student',
            name='Profile_pic',
            field=models.ImageField(upload_to=students.models.path_and_rename),
        ),
    ]
