# Generated by Django 3.1.2 on 2020-10-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Roll_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
