# Generated by Django 3.0.8 on 2020-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200813_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Class',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
