# Generated by Django 3.0.8 on 2020-07-26 20:28

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Address', models.TextField()),
                ('Contact_Phone_1', models.CharField(max_length=10)),
                ('Contact_Phone_2', models.CharField(blank=True, max_length=10)),
                ('Contact_Email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(default='default.jpg', upload_to=schools.models.path_and_rename)),
            ],
        ),
    ]
