# Generated by Django 3.1.2 on 2020-10-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user'),
        ('schools', '0003_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
