# Generated by Django 3.1 on 2020-08-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200824_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Absent',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
